name: Build-Workflow
on: [push, pull_request]
jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    env: 
        working-directory: backEndEngine
    steps:

    - name: Set up Go 1.15
      uses: actions/setup-go@v1
      with:
        go-version: 1.15.3
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2
      
    - name: Show the folder we're in
      run: ls -al
      
    - name: Run Go Tidy
      run:  go mod tidy
      working-directory: ${{env.working-directory}}
        
    - name: Build backendEngine
      run: go build
      working-directory: ${{env.working-directory}}
        
